name: "Pipeline"
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --immutable
      - run: yarn moon ci
